# Generated by Django 6.0.3 on 2026-03-20 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_technology_project_technologies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tech_stack',
        ),
    ]
