# Generated by Django 6.0.3 on 2026-09-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('qualification', models.CharField(max_length=150)),
                ('graduation_year', models.PositiveIntegerField()),
                ('experience', models.CharField(choices=[('Fresher', 'Fresher'), ('Experienced', 'Experienced')], max_length=20)),
                ('skills', models.TextField()),
                ('preferred_location', models.CharField(max_length=150)),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='referral/resumes/')),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
