# Generated by Django 6.0.3 on 2026-09-18 13:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0002_alter_referralapplication_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralapplication',
            name='resume',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='resume'),
        ),
    ]
