# Generated by Django 6.0.3 on 2026-09-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0003_alter_referralapplication_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralapplication',
            name='current_company_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='referralapplication',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
