# Generated by Django 6.0.3 on 2026-03-20 12:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-percentage'], 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AddField(
            model_name='skill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, help_text='Enter FontAwesome class (e.g. fa-brands fa-python)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='type',
            field=models.CharField(choices=[('technical', 'Technical'), ('behavioral', 'Behavioral')], default='technical', max_length=20),
        ),
        migrations.AlterField(
            model_name='skill',
            name='percentage',
            field=models.PositiveIntegerField(),
        ),
    ]
