# Generated by Django 6.0.3 on 2026-03-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0002_alter_skill_options_skill_created_at_skill_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='type',
            field=models.CharField(choices=[('technical', 'Technical'), ('tools', 'Tools')], default='technical', max_length=20),
        ),
    ]
