# Generated by Django 6.0.3 on 2026-03-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0003_alter_skill_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='icon',
            field=models.CharField(default='jn', max_length=100),
        ),
    ]
