# Generated by Django 6.0.3 on 2026-03-21 03:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0004_sociallink_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociallink',
            options={'ordering': ['platform']},
        ),
        migrations.AddField(
            model_name='sociallink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='icon',
            field=models.CharField(default='fa-solid fa-link', help_text='Enter FontAwesome class (e.g. fa-brands fa-github)', max_length=100),
        ),
    ]
