# Generated by Django 6.0.3 on 2026-03-23 07:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0006_certification_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='project',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
