# Generated by Django 6.0.3 on 2026-03-24 05:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0009_delete_customuser_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
