# Generated by Django 6.0.3 on 2026-03-24 06:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0010_alter_profile_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='resume'),
        ),
    ]
